###############################################################################
#        Example instruction file for the Modular Megafauna Model
#        ========================================================
#
# Please read the Doxygen documentation to learn how to use this instruction
# file.
###############################################################################

[simulation]

establishment_interval = 3650 # every 10 years
forage_distribution    = "Equally"
habitat_area_km2       = 1.0  # km² per habitat
herbivore_type         = "Cohort"
metabolizable_energy   = { grass = 15.0 } # MJ/kgDM
one_hft_per_habitat    = true

[output]
format = "TextTables"
interval = "Annual"

[output.text_tables]
directory = "."
precision = 4
tables = [
  "digestibility",
  "mass_density_per_hft"
]

###############################################################################

[[group]]
name = "all_hfts"

[group.body_fat]
birth = 0.2
# ...

# Add any HFT parameters here, but prefix the tables/sections with "group."
# instead of "hft.". Any HFT parameter that is not found in the HFT table
# itself will be taken from the groups the HFT belongs to.

[[group]]
name = "hindguts"
[group.digestion]
efficiency   = 0.93
i_g_1992_ijk = [0.108, 3.284, 0.080]

[[group]]
name = "ruminants"
[group.digestion]
efficiency   = 1.0
i_g_1992_ijk = [0.034, 3.565, 0.077]

###############################################################################

[[hft]]

name   = "example"
groups = [ "ruminants", "all_hfts" ] # first overrides last group

[hft.body_fat]
birth              = 0.2   # kg/kg
deviation          = 0.125 # body condition
maximum            = 0.3   # kg/kg
maximum_daily_gain = 0.05  # kg/kg/day

[hft.body_mass]
birth  = 5  # kg/ind
female = 50 # kg/ind
male   = 70 # kg/ind

[hft.breeding_season]
length = 30  # days
start  = 121 # Julian day

[hft.digestion]
allometric             = { coefficient = 0.050, exponent = 0.76 }
anabolism_coefficient  = 54.6 # MJ/kg
catabolism_coefficient = 39.3 # MJ/kg
fixed_fraction         = 0.05 # kgDM per kg body mass
limit                  = "FixedFraction"

[hft.establishment]
age_range = { first = 1, last = 15 } # years
density   = 1.0       # ind/km²

[hft.expenditure]
allometric = { coefficient = 0.4, exponent = 0.75 }
components = [ "Allometric" ]

[hft.foraging]
diet_composer           = "PureGrazer"
half_max_intake_density = 20 # gDM/m²
limits                  = []
net_energy_model        = "Default"

[hft.life_history]
lifespan                 = 16 # years
physical_maturity_female = 3  # years
physical_maturity_male   = 3  # years
sexual_maturity          = 3  # years

[hft.mortality]
adult_rate = 0.1 # 1/year
factors = [ "Background", "Lifespan", "StarvationIlliusOConnor2000" ]
juvenile_rate = 0.3 # 1/year
minimum_density_threshold = 0.5 # fraction of establishment density
shift_body_condition_for_starvation = true

[hft.reproduction]
annual_maximum   = 1.0 # offspring per female per year
gestation_length = 9   # months
model            = "ConstantMaximum"

[hft.thermoregulation]
conductance = "BradleyDeavers1980"
core_temperature = 38 # °C

###############################################################################
# You can add more HFTs like so:
# [[hft]]
# name = "new_hft"
# [hft.body_fat]
# ...
